#! /bin/sh

sxhkd &
wal -R -a 80
compton &
polybar bar -r &

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"

bspc monitor DP-0 -d I II III IV V VI VII VIII IX X
#bspc monitor DP0 -d I III V VII IX 
#bspc monitor HDMI0 -d II IV VI VIII X

outer_gap=50
bspc config border_width         2
bspc config window_gap          100
bspc config top_padding $outer_gap
bspc config bottom_padding $outer_gap
bspc config left_padding $outer_gap
bspc config right_padding $outer_gap

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
